version: '3.5'

services:
  myorders-app:
    build: 
      context: './docker-assets/php/'
      args:
        UID: ${UID}
        WEB_USER: ${WEB_USER}
        WEB_GROUP: ${WEB_GROUP}
    container_name: ${APP_NAME}_php
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8080:80
    networks:
      backend:
        aliases:
          - ${APP_NAME}_php
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"
    dns_search: mysql
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    container_name: ${APP_NAME}_mysql
    networks:
      backend:
        aliases:
          - db

networks:
  backend:
    name: backend-network